version: '3.3'
services:
  my-annotations-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'henrique-mind'
      MYSQL_USER: 'usr_henrique-mind'
      MYSQL_PASSWORD: 'henriquemind'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - henrique-mind-db:/var/lib/mysql

volumes:
  henrique-mind-db: